import logging
import glob
import os

import numpy as np

import h5py
import scipy.io

from . import functions as func
from .collections import dotdict


class Dataset:
    """
    This class is for loading empirical Datasets. Datasets are stored as matrices and can
    include functional (e.g. fMRI) and structural (e.g. DTI) data.

    ## Format

    Empirical datasets are
    stored in the `neurolib/data/datasets` directory. In each dataset, subject-wise functional
    and structural data is stored as MATLAB `.mat` matrices that can be opened in
    Python using SciPy's `loadmat` function. Structural data are
    $N \\times N$, and functional time series are $N \\times t$ matrices, $N$ being the number
    of brain regions and $t$ the number of time steps. Example datasets are included in `neurolib`
    and custom datasets can be added by placing them in the dataset directory.

    ## Structural DTI data

    To simulate a whole-brain network model, first we need to load the structural connectivity
    matrices from a DTI data set. The matrices are usually a result of processing DTI data and
    performing fiber tractography using software like *FSL* or
    *DSIStudio*. The handling of the datasets is done by the
    `Dataset` class, and the attributes in the following refer to its instances.
    Upon initialization, the subject-wise data set is loaded from disk. For all examples
    in this paper, we use freely available data from the ConnectomeDB of the
    Human Connectome Project (HCP). For a given parcellation of the brain
    into $N$ brain regions, these matrices are the $N \\times N$ adjacency matrix `self.Cmat`,
    i.e. the structural connectivity matrix, which determines the coupling strengths between
    brain areas, and the fiber length matrix `Dmat` which determines the signal
    transmission delays. The two example datasets currently included in `neurolib` use the the 80
    cortical regions of the AAL2 atlas to define the brain areas and are
    sorted in a LRLR-ordering.


    ## Connectivity matrix normalization

    The elements of the structural connectivity matrix `Cmat` are typically the number
    of reconstructed fibers from DTI tractography. Since the number of fibers depends on the
    method and the parameters of the (probabilistic or deterministic) tractography, they need to
    be normalized using one of the three implemented methods. The first method `max` is to
    simply divide the entries of  `Cmat` by the largest entry, such that the the largest
    entry becomes 1. The second method  `waytotal` divides the entries of each column of
    `Cmat` by the number fiber tracts generated from the respective brain region during
    probabilistic tractography in FSL, which is contained in the `waytotal.txt` file.
    The third method `nvoxel` divides the entries of each column of `Cmat` by the
    size, e.g., the number of voxels of the corresponding brain area. The last two methods yield
    an asymmetric connectivity matrix, while the first one keeps `Cmat` symmetric.
    All normalization steps are done on the subject-wise matrices `Cmats` and
    `Dmats`. In a final step, all matrices can also be averaged across all subjects
    to yield one `Cmat` and `Dmat` per dataset.

    ## Functional MRI data

    Subject-wise fMRI time series must be in a $(N \\times t)$-dimensional format, where $N$ is the
    number of brain regions and $t$ the length of the time series. Each region-wise time series
    represents the BOLD activity averaged across all voxels of that region, which can be also obtained
    from software like FSL. Functional connectivity (FC) captures the spatial correlation structure
    of the BOLD time series averaged across the entire time of the recording. FC matrices are
    accessible via the attribute `FCs` and are generated by computing the Pearson correlation
    of the time series between all regions, yielding a $N \\times N$ matrix for each subject.

    To capture the temporal fluctuations of time-dependent FC(t), which are lost when averaging
    across the entire recording time, functional connectivity dynamics matrices (`FCDs`) are
    computed as the element-wise Pearson correlation of time-dependent FC(t) matrices in a moving
    window across the BOLD time series of a chosen window length of, for example, 1 min. This
    yields a $t_{FCD} \\times t_{FCD}$ FCD matrix for each subject, with $t_{FCD}$ being the number
    of steps the window was moved.

    """

    def __init__(self, datasetName=None, normalizeCmats="max", fcd=False, subcortical=False):
        """
        Load the empirical data sets that are provided with `neurolib`.

        Right now, datasets work on a per-subject base. A dataset must be located
        in the `neurolib/data/datasets/` directory. Each subject's dataset
        must be in the `subjects` subdirectory of that folder. In each subject
        folder there is a directory called `functional` for time series data
        and `structural` the structural connectivity data.

        See `loadData.loadSubjectFiles()` for more details on which files are
        being loaded.

        The structural connectivity data (accessible using the attribute
        loadData.Cmat), can be normalized using the `normalizeCmats` flag.
        This defaults to "max" which normalizes the Cmat by its maxmimum.
        Other options are `waytotal` or `nvoxel`, which normalizes the
        Cmat by dividing every row of the matrix by the waytotal or
        nvoxel files that are provided in the datasets.

        Info: the waytotal.txt and the nvoxel.txt are files extracted from
        the tractography of DTI data using `probtrackX` from the `fsl` pipeline.

        Individual subject data is provided with the class attributes:
        self.BOLDs: BOLD timeseries of each individual
        self.FCs: Functional connectivity of BOLD timeseries

        Mean data is provided with the class attributes:
        self.Cmat: Structural connectivity matrix (for coupling strenghts between areas)
        self.Dmat: Fiber length matrix (for delays)
        self.BOLDs: BOLD timeseries of each area
        self.FCs: Functional connectiviy matrices of each BOLD timeseries

        :param datasetName: Name of the dataset to load
        :type datasetName: str
        :param normalizeCmats: Normalization method for the structural connectivity matrix. normalizationMethods = ["max", "waytotal", "nvoxel"]
        :type normalizeCmats: str
        :param fcd: Compute FCD matrices of BOLD data, defaults to False
        :type fcd: bool
        :param subcortical: Include subcortical areas from the atlas or not, defaults to False
        :type subcortical: bool

        """
        self.has_subjects = None
        if datasetName:
            self.loadDataset(datasetName, normalizeCmats=normalizeCmats, fcd=fcd, subcortical=subcortical)

    def loadDataset(self, datasetName, normalizeCmats="max", fcd=False, subcortical=False):
        """Load data into accessible class attributes.

        :param datasetName: Name of the dataset (must be in `datasets` directory)
        :type datasetName: str
        :param normalizeCmats: Normalization method for Cmats, defaults to "max"
        :type normalizeCmats: str, optional
        :raises NotImplementedError: If unknown normalization method is used
        """
        pass

    def computeFCD(self):
        pass

    def getDataPerSubject(
        self,
        name,
        apply="single",
        apply_function=None,
        apply_function_kwargs={},
        normalizeCmats="max",
    ):
        """Load data of a certain kind for all users of the current dataset

        :param name: Name of data type, i.e. "bold" or "cm"
        :type name: str
        :param apply: Apply function per subject ("single") or on all subjects ("all"), defaults to "single"
        :type apply: str, optional
        :param apply_function: Apply function on data, defaults to None
        :type apply_function: function, optional
        :param apply_function_kwargs: Keyword arguments of fuction, defaults to {}
        :type apply_function_kwargs: dict, optional
        :return: Subjectwise data, after function apply
        :rtype: list[np.ndarray]
        """
        pass

    def _normalizeCmats(self, Cmats, method="max", FSL_SAMPLES_PER_VOXEL=5000):
        # normalize per subject data
        pass

    def _loadSubjectFiles(self, dsBaseDirectory, subcortical=False):
        """Dirty subject-wise file loader. Depends on the exact naming of all
        files as provided in the `neurolib/data/datasets` directory. Uses `glob.glob()`
        to find all files based on hardcoded file name matching.

        Can filter out subcortical regions from the AAL2 atlas.

        Info: Dirty implementation that assumes a lot of things about the dataset and filenames.

        :param dsBaseDirectory: Base directory of the dataset
        :type dsBaseDirectory: str
        :param subcortical: Filter subcortical regions from files defined by the AAL2 atlas, defaults to False
        :type subcortical: bool, optional
        """
        pass

    def loadMatrix(self, matFileName, key="", verbose=False):
        """Function to furiously load .mat files with scipy.io.loadmat.
        Info: More formats are supported but commented out in the code.

        :param matFileName: Filename of matrix to load
        :type matFileName: str
        :param key: .mat file key in which data is stored (example: "sc")
        :type key: str

        :return: Loaded matrix
        :rtype: numpy.ndarray
        """
        pass


def filterSubcortical(a, axis="both"):
    """
    Filter out subcortical areas out of AAL2 atlas
    Indices from https://github.com/spunt/bspmview/blob/master/supportfiles/AAL2_README.txt
    Reminder: these are AAL indices, they start at 1!!!

    Hippocampus: 41 - 44
    Amygdala: 45-46
    Basal Ganglia: 75-80
    Thalamus: 81-82
    Cerebellum: 95-120

    :param a: Input (square) matrix with cortical and subcortical areas
    :type a: numpy.ndarray

    :return: Matrix without subcortical areas
    :rtype: numpy.ndarray
    """
    pass
